### PR TITLE
feat: add built in logging

### PR DESCRIPTION
**Pull request by anddddrew**
ref #10, I believe this should work. Let me know though

### CODE REVIEW

**Review by heybereket — APPROVED** [review]

**Comment by anddddrew** [comment]
CI is failing, let me fix that rq

**Comment by alii** [comment]
Where are these exported? e.g. are they publicly avail externally?

**Comment by heybereket** [comment]
> Where are these exported? e.g. are they publicly avail externally?

@anddddrew Export the file in index.ts:
`export * from ./logger`

**Comment by anddddrew** [comment]
> > Where are these exported? e.g. are they publicly avail externally?
> 
> @anddddrew Export the file in index.ts: `export * from ./logger`

Oops, I completely forgot that. Just created a commit to fix that

**Comment by alii** [comment]
lgtm :)

**Review by alii — APPROVED** [review]

**Comment by alii** [comment]
poss to fix ci issue there, then we can merge

**Comment by anddddrew** [comment]
> poss to fix ci issue there, then we can merge

yep looking at that right now.

**Comment by anddddrew** [comment]
@alii Just fixed the issue, sorry for being late I was at school 😓

**Comment by alii** [comment]
np, think the lockfile is still needing a merge tho as ci is failing still unfortunately. i think `yarn` will resolve it and then you can commit & push :)

**Comment by anddddrew** [comment]
> np, think the lockfile is still needing a merge tho as ci is failing still unfortunately. i think `yarn` will resolve it and then you can commit & push :)

fixed, had to turn off member accessibility in eslint (I could have just done it for the single file (logger.ts), but I don't think this is a big issue?)

**Comment by alii** [comment]
in future waiting would be great but all good np, thank you very much!

**Comment by alii** [comment]
Fixed in d26116f39a4f3dd56c1aab2e076bd6235e4bc716

**Comment by anddddrew** [comment]
> in future waiting would be great but all good np, thank you very much!
> 
> we will need that eslint rule on hence why waiting would be better, so ill fix that now and update that :)

Gotcha, I'll make sure to wait next time for you :)

**Pull request merged**
